# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('myKitty_timesTwo', PACKAGE = 'myKitty', x)
}

write_vcf_body <- function(fix, gt, filename, mask = 0L) {
    invisible(.Call('myKitty_write_vcf_body', PACKAGE = 'myKitty', fix, gt, filename, mask))
}

#'
#' @title test_gz_write
#' @description test of writing gz file
#'
#' @param filename name for created file
#' @param mask integer
#'
#' @details test of writing gz file
#'
#'
#' @export
test_gz_write <- function(filename = "myFile.gz", mask = 0L) {
    invisible(.Call('myKitty_test_gz_write', PACKAGE = 'myKitty', filename, mask))
}

